
<?php 
	// path
	define("ROOT",dirname(__DIR__));
	define("MODElS",ROOT.DIRECTORY_SEPARATOR."mvc".DIRECTORY_SEPARATOR."models".DIRECTORY_SEPARATOR);
	define("VIEWS",ROOT.DIRECTORY_SEPARATOR."mvc".DIRECTORY_SEPARATOR."views".DIRECTORY_SEPARATOR);
	define("CONTROLLERS",ROOT.DIRECTORY_SEPARATOR."mvc".DIRECTORY_SEPARATOR."controllers".DIRECTORY_SEPARATOR);
	define("CORE",ROOT.DIRECTORY_SEPARATOR."mvc".DIRECTORY_SEPARATOR."core".DIRECTORY_SEPARATOR);
	define("FILES",ROOT.DIRECTORY_SEPARATOR."mvc".DIRECTORY_SEPARATOR."files".DIRECTORY_SEPARATOR);
	// database
	define("DB_HOST", "sql12.freemysqlhosting.net");
	define("DB_USER", "sql12358640");
	define("DB_PASS", "w8lfuMNaRg");
	define("DB_NAME", "sql12358640");

